# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mjishnu.raven
PackageVersion: 1.1.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Raven.exe
  PortableCommandAlias: raven
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mjishnu/Raven/releases/download/v1.1.2.1/Raven-v1.1.2.1-win-x86-self-contained.zip
  InstallerSha256: E7A9D6428D88ACFF33C8897081F2A7EF7B55D807E6DE4F12C1580CBCF13010B9
- Architecture: x64
  InstallerUrl: https://github.com/mjishnu/Raven/releases/download/v1.1.2.1/Raven-v1.1.2.1-win-x64-self-contained.zip
  InstallerSha256: 56A57095D71000F95315A7641E484D344F2C91AFAB08F4B4E9E1872A1C699767
- Architecture: arm64
  InstallerUrl: https://github.com/mjishnu/Raven/releases/download/v1.1.2.1/Raven-v1.1.2.1-win-arm64-self-contained.zip
  InstallerSha256: 1A1CFB8A81653E000878CCA4CB9107E1BFED4A5B611BF933C91082136642AC53
ManifestType: installer
ManifestVersion: 1.12.0
